name: scrap3

on:
  schedule:
    - cron: '0 0 12 ? * SUN' #the schedule, in this case every Mon,Wed,Fri at 22:00, in cron time (https://www.freeformatter.com/cron-expression-generator-quartz.html)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: python scrape.py #NAME OF YOUR FILE HERE!!
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
